telegram.bot.token: ${BOT_TOKEN}

rbkch.chat.id: ${CHAT_ID}
rbkch.retra.link: ${RETRA_LINK}
rbkch.chats: ${CHATS}

kuranda:
  id: ${KURANDA_ID}

sasha:
  id: ${SASHA_ID}

tolik:
  id: ${TOLIK_ID}

server:
  port: ${PORT}

my.id: ${MY_ID}
