hosted.url: ${HOSTED_URL:localhost}
telegram.bot.token: ${BOT_TOKEN}
#
#rbkch.chat.id: ${CHAT_ID}
#rbkch.retra.link: ${RETRA_LINK}
#rbkch.chats: ${CHATS}
#
#kuranda:
#  id: ${KURANDA_ID}
#
#sasha:
#  id: ${SASHA_ID}
#
#server:
#  port: ${PORT}
#
admin.id: ${MY_ID:123}
